# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from abc import ABC

from msrest import Deserializer, Serializer

from azure.core import PipelineClient

from ._configuration import MergePatchJsonClientConfiguration


class MixinABC(ABC):
    _client: PipelineClient
    _config: MergePatchJsonClientConfiguration
    _serializer: Serializer
    _deserializer: Deserializer
